#Properties
alfresco-connector.version=0.0.7-R20100908
crypto-api.version=1.0.3
dms-connector.version=0.0.7-R20100908
iflow.baseversion=4.2.6
iflow.buildnumber=20180704
iflow.home=C\:\\Users\\jcosta\\git\\iFlowRoot\\iflow-blocks/iflow-home
iflow.version=4.2.6-R20180704
maven.test.skip=true
project.build.sourceEncoding=UTF-8
