drop table if exists cma_tipo_processo;

-- para requerimentos
create table cma_tipo_processo (
  id_tipo_processo varchar(64),
  id_tipo_processo_num integer,
  grupo varchar(60),
  codigo_subgrupo varchar(64),
  subgrupo varchar(60),
  id_tipo_requerimento integer,
  pasta_processo_base varchar(200),
  tipo_processo_macro char(1),
  perfil_responsavel varchar(100),
  descricao varchar(200)
);


insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OP_LOTEAMENTO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','1','Arquivo/CMA/10-Urbanismo/Loteamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para operação de loteamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OBRAS_URBANIZACAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','2','Arquivo/CMA/10-Urbanismo/Loteamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OBRAS_EDIFICACAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','3','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para obras de edificação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OBRAS_ALTERACAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','4','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias /$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para obras de alteração');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OBRAS_AMPLIACAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','5','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para obras de ampliação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OBRAS_DEMOLICAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','6','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias /$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para obras de demolição');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_ALTERACAO_UTILIZACAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','7','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias /$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para alteração de utilização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_OUTRAS_OBRAS','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','8','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias /$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para outras operações urbanísticas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_IP_RECONSTRUCAO','1','URBANISMO','adHoc_Ext_URB_INFORMACAO_PREVIA','Informação Prévia','62','Arquivo/CMA/10-Urbanismo/Obras particulares/Informações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Informação prévia para reconstrução');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OBRAS_CONSTRUCAO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','9','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para obras de construção ');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OBRAS_ALTERACAO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','10','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para obras de alteração');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OBRAS_AMPLIACAO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','11','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para obras de ampliação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_RECONST_COM_PRESER_FACHADA','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','12','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para obras de reconstrução com preservação de fachada');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_REMODEL_TERRENOS','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','13','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para trabalhos de remodelação de terrenos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OP_LOTEAMENTO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','14','Arquivo/CMA/10-Urbanismo/Loteamentos/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para operação de loteamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OBRAS_URBANIZACAO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','15','Arquivo/CMA/10-Urbanismo/Loteamentos/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação prévia para obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CP_OBRAS_DEMOLICAO','2','URBANISMO','adHoc_Ext_URB_COMUNICACAO_PREVIA','Comunicação Prévia','63','Arquivo/CMA/10-Urbanismo/Obras particulares/Comunicações prévias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Comunicação Prévia para obras de demolição');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OBRAS_CONSTRUCAO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','16','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de construção');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OBRAS_ALTERACAO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','17','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de alteração');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OBRAS_AMPLIACAO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','18','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de ampliação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_RECONST_SEM_PRESER_FACHADA','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','19','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de reconstrução sem preservação de fachada');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OBRAS_DEMOLICAO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','20','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de demolição');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_REMODEL_TERRENOS','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','21','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de trabalhos de remodelação de terrenos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OP_LOTEAMENTO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','22','Arquivo/CMA/10-Urbanismo/Loteamento/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de operação de loteamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_OBRAS_URBANIZACAO','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','23','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento de obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_LIC_ARMAZ_COMBUSTIVEIS','3','URBANISMO','adHoc_Ext_URB_LICENCIAMENTO','Licenciamento','24','Arquivo/CMA/10-Urbanismo/Obras particulares/Licenciamentos/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licenciamento simplificado - Instalação  de armazenamento de combustíveis');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_AUT_UTILIZACAO','4','URBANISMO','adHoc_Ext_URB_AUTORIZACAO','Autorização de utilização/alteração','27','Arquivo/CMA/10-Urbanismo/Obras particulares/Autorizações de utilização/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Autorização de utilização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_AUT_ALTERACAO_UTIL','4','URBANISMO','adHoc_Ext_URB_AUTORIZACAO','Autorização de utilização/alteração','28','Arquivo/CMA/10-Urbanismo/Obras particulares/Alterações de utilização/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Alteração de utilização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_LOTEAMENTO','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','25','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Alteração de alvará de loteamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_CONST_ESTRUTURA','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','26','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Alvará de licença parcial para construção de estrutura');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_OBRAS_EDIFICACAO','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','29','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Emissão de alvará para obras de edificação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_OP_LOTEAMENTO','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','31','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Emissão de alvará para operações de loteamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_OBRAS_URBANIZACAO','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','32','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Emissão de alvará para obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_REMODEL_TERRENOS','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','33','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Emissão de alvará para trabalhos de remodelação de terrenos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_ALV_OUTRAS_OPERACOES','5','URBANISMO','adHoc_Ext_URB_EMISSAO_ALVARAS','Emissão de Alvarás','34','Arquivo/CMA/10-Urbanismo/Alvarás/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Emissão de alvará para outras operações urbanísticas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_REN_ART_72','6','URBANISMO','adHoc_Ext_URB_RENOVACAO','Renovação/Licença Especial','35','Arquivo/CMA/10-Urbanismo/Licenças/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Renovação de licença ou comunicação prévia (artigo 72.º do RJUE)');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_REN_ART_88','6','URBANISMO','adHoc_Ext_URB_RENOVACAO','Renovação/Licença Especial','36','Arquivo/CMA/10-Urbanismo/Licenças/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Licença especial para obras inacabadas (artigo 88.º do RJUE)');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_DESTAQUE','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','37','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de destaque');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_PROP_HORIZONTAL','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','38','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de propriedade horizontal');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_CONSTRUCOES_PRE51_69','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','39','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de construções anteriores a 07.08.1951 ou 14.01.1969');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_COMPROPRIEDADE','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','40','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de constituição de compropriedade');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_LIC_UTILIZACAO','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','41','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de licença de utilização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_NUMER_POLICIA','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','42','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de numeração de policia');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_CER_GARANTIA_EXEC','7','URBANISMO','adHoc_Ext_URB_CERTIDOES','Certidões','43','Arquivo/CMA/10-Urbanismo/Certidões/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Certidão de garantia de execução de obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_RESTAURACAO','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','44','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para estabelecimentos de restauração e bebidas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_ARMAZ_COMBUSTIVEL','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','45','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para instalação de armazenamento de combustíveis');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_ACTIV_INDUSTRIAL','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','46','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para licenciamento actividade industrial');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_SEG_SALUBRIDADE','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','47','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para verificação das condições de segurança e salubridade');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_RECEP_PROVISORIA','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','48','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para recepção provisória  das obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_VIS_RECEP_DEFINITIVA','8','URBANISMO','adHoc_Ext_URB_VISTORIAS','Vistorias','49','Arquivo/CMA/10-Urbanismo/Vistorias/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Vistoria para recepção definitiva  das obras de urbanização');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_INS_PLANEAMENTO_TERRITORIAL','12','URBANISMO','adHoc_Ext_URB_PLANEAMENTO','Planeamento Territorial','61','Arquivo/CMA/10-Urbanismo/Planeamento territorial/$NOME_DA_FREGUESIA','E','Atendimento_DOGU',' Instrumentos de planeamento territorial/indicadores urbanísticos ');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_AVERBAMENTO','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','50','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU','Averbamento (urbanismo)');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_COM_INICIO_OBRA','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','51','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU',' Comunicação de início de obra');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_JUNCAO_ELEMENTOS','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','52','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU',' Junção de elementos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_PROJ_ESPECIALIDADE','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','53','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU',' Projectos de especialidade');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_PRORROGACAO_PRAZOS','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','54','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU',' Prorrogação de prazos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_URB_PC_OCUPACAO_VIA_PUBLICA','11','URBANISMO','adHoc_Ext_URB_PROC_COMPLEMENTARES','Processos Complementares','55','Arquivo/CMA/10-Urbanismo/Diversos','E','Atendimento_DOGU',' Ocupação de via pública');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DIV_PEDIDOS','9','PEDIDOS_DIVERSOS','adHoc_Ext_DIV_PEDIDOS','','56','Arquivo/CMA/Pedidos diversos','E','Atendimento_DOGU_Expediente',' Pedidos diversos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DOCS_ACESSO','10','ACESSO A DOCUMENTOS ADMINISTRATIVOS','adHoc_Ext_DOCS_ACESSO','','57','Arquivo/CMA/Pedidos de acesso e ou reprodução de processo ou licença','E','Todos',' Consulta e reprodução de documentos ');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_PEDRA_SEPULTURA','','CEMITÉRIOS','adHoc_Ext_CEM_PEDRA_SEPULTURA','','58','Arquivo/CMA/12-Serviços urbanos/Cemitérios','E','Atendimento_DSU',' Colocação de pedra em sepultura');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_SEG_VIA_ALVARA','','CEMITÉRIOS','adHoc_Ext_CEM_SEG_VIA_ALVARA','','59','Arquivo/CMA/12-Serviços urbanos/Cemitérios','E','Atendimento_DSU',' 2ª via do alvará de sepultura');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_AVERBAMENTO','','CEMITÉRIOS','adHoc_Ext_CEM_AVERBAMENTO','','60','Arquivo/CMA/12-Serviços urbanos/Cemitérios','E','Atendimento_DSU',' Averbamento de alvará');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_COVAL','','CEMITÉRIOS','adHoc_Ext_CEM_COVAL','','61','Arquivo/CMA/12-Serviços urbanos/Cemitérios','E','Atendimento_DSU',' Concessão de coval (Edital nº 12/06)');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_CREMACAO','','CEMITÉRIOS','adHoc_Ext_CEM_CREMACAO','','62','Arquivo/CMA/12-Serviços urbanos/Cemitérios/Inumações ou cremações','E','Atendimento_DSU',' Inumação ou cremação');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CEM_TRANSLADACAO','','CEMITÉRIOS','adHoc_Ext_CEM_TRANSLADACAO','','63','Arquivo/CMA/12-Serviços urbanos/Cemitérios/Trasladações de cadáveres ou ossadas','E','Atendimento_DSU',' Trasladação de cadáveres ou ossadas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_TRANS_ART_50','','TRANSPORTES E TRÂNSITO','adHoc_Ext_TRANS_ART_50','','64','Arquivo/CMA/12-Serviços urbanos/Viação e trânsito','E','Atendimento_DSU',' Estacionamento proibido - Art. 50 Código de Estrada');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_TRANS_AUTOCARRO','','TRANSPORTES E TRÂNSITO','adHoc_Ext_TRANS_AUTOCARRO','','65','Arquivo/CMA/17-Apoio e manutenção/Transportes/Candidaturas à utilização de autocarro municipal','E','Atendimento_DMT','Candidatura à utilização de autocarro municipal');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_TRANS_TAXIS','','TRANSPORTES E TRÂNSITO','adHoc_Ext_TRANS_TAXIS','','66','Arquivo/CMA/12-Serviços urbanos/Taxis','E','Atendimento_DSU','Táxis');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_TRANS_MATRICULA_CICLOMOTORES','','TRANSPORTES E TRÂNSITO','adHoc_Ext_TRANS_MATRICULA_CICLOMOTORES','','67','Arquivo/CMA/0.2-Serviços administrativos/Taxas e licenças/Ciclomotores','E','Atendimento_DSU','Certificado de matrícula - Ciclomotores');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_AMB_RUIDO','','AMBIENTE E ESPAÇOS VERDES','adHoc_Ext_AMB_RUIDO','','68','Arquivo/CMA/12-Serviços urbanos/Assuntos ambientais/Licenças de ruído','E','Atendimento_DOGU',' Licença de ruído ');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_AMB_DESTRUICAO_VEGETAL','','AMBIENTE E ESPAÇOS VERDES','adHoc_Ext_AMB_DESTRUICAO_VEGETAL','','69','Arquivo/CMA/12-Serviços urbanos/Assuntos ambientais','E','Atendimento_DOGU',' Acções de destruição do revestimento vegetal para fins não agricolas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_PROVAS','','DESPORTO E RECREIO','adHoc_Ext_DESP_PROVAS','','70','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento_DSU_DDJ',' Provas desportivas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_ARRAIAIS','','DESPORTO E RECREIO','adHoc_Ext_DESP_ARRAIAIS','','71','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento ',' Arraiais, romarias, bailes e outros divertimentos públicos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_MAQ_DIVERSAO','','DESPORTO E RECREIO','adHoc_Ext_DESP_MAQ_DIVERSAO','','72','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento ',' Licença de utilização de máquinas de diversão');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_MAQ_MOD_423','','DESPORTO E RECREIO','adHoc_Ext_DESP_MAQ_MOD_423','','73','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento ',' Máquinas de diversão - Mod. 423');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_RECINTOS','','DESPORTO E RECREIO','adHoc_Ext_DESP_RECINTOS','','74','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento ',' Licença de utilização para recintos de espéctaculos de natureza não artística');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_RECINTO_ITENERANTE','','DESPORTO E RECREIO','adHoc_Ext_DESP_RECINTO_ITENERANTE','','75','Arquivo/CMA/16-Cultura desporto e recreio/Desporto e recreio','E','Atendimento ',' Licenciamento da instalação de recinto itenerante/improvisado/diversão provisória');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_DESP_CARTA_CACADOR','','DESPORTO E RECREIO','adHoc_Ext_DESP_CARTA_CACADOR','','76','Arquivo/CMA/0.2-Serviços administrativos/Taxas e licenças/Carta de caçador','E','Atendimento ',' Carta de caçador');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_MERC_MERCADO_DIARIO','','MERCADOS E FEIRAS','adHoc_Ext_MERC_MERCADO_DIARIO','','77','Arquivo/CMA/12-Serviços urbanos/Mercados e feiras','E','Atendimento_DSU',' Mercado diário municipal');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_MERC_FEIRA_SEMANAL','','MERCADOS E FEIRAS','adHoc_Ext_MERC_FEIRA_SEMANAL','','78','Arquivo/CMA/12-Serviços urbanos/Mercados e feiras','E','Atendimento_DSU',' Feira semanal de Abrantes');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_MERC_MERCADO_SEMANAL_GROSSO','','MERCADOS E FEIRAS','adHoc_Ext_MERC_MERCADO_SEMANAL_GROSSO','','79','Arquivo/CMA/12-Serviços urbanos/Mercados e feiras','E','Atendimento_DSU',' Mercado semanal de Abrantes comércio por grosso');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_MERC_S_MATIAS','','MERCADOS E FEIRAS','adHoc_Ext_MERC_S_MATIAS','','80','Arquivo/CMA/12-Serviços urbanos/Mercados e feiras','E','Atendimento_DSU',' Feira de S. Matias');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_EST_HORARIO','','ESTABELECIMENTOS','adHoc_Ext_EST_HORARIO','','81','Arquivo/CMA/0.9-Actividades económicas','E','Atendimento ','Horário de funcionamento de estabelecimento ');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_EST_DECL_INSTAL_COMERCIAIS','','ESTABELECIMENTOS','adHoc_Ext_EST_DECL_INSTAL_COMERCIAIS','','82','Arquivo/CMA/0.9-Actividades económicas','E','Atendimento ','Declaração de instalação, modificação e de encerramento dos estabelecimentos comerciais e de serviços');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_EST_DECL_INSTAL_RESTAURACAO','','ESTABELECIMENTOS','adHoc_Ext_EST_DECL_INSTAL_RESTAURACAO','','83','Arquivo/CMA/0.9-Actividades económicas','E','Atendimento ','Declaração de instalação, modificação e de encerramento dos estabelecimentos de restauração ou de bebidas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_VEND_UNIDADE_MOVEL','','VENDA AMBULANTE','adHoc_Ext_VEND_UNIDADE_MOVEL','','84','Arquivo/CMA/0.9-Actividades económicas/Comércio e serviços/Vendedores ambulantes e feirantes','E','Atendimento_DSU','Unidade móvel para venda de produtos alimentares');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_VEND_VENDEDOR','','VENDA AMBULANTE','adHoc_Ext_VEND_VENDEDOR','','85','Arquivo/CMA/0.9-Actividades económicas/Comércio e serviços/Vendedores ambulantes e feirantes','E','Atendimento ','Vendedor ambulante');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_CONTROLO_METROLOGIA','','CONTROLO DE METROLOGIA','adHoc_Ext_CONTROLO_METROLOGIA','','86','Arquivo/CMA/0.9-Actividades económicas/Comércio/Aferições','E','Atendimento_DSU','Controlo de metrologia');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_PUB_LICENCAS','','PUBLICIDADE','adHoc_Ext_PUB_LICENCAS','','87','Arquivo/CMA/0.9-Actividades económicas/Industria/Publicidade','E','Atendimento ','Licenças de publicidade');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_PUB_SINAIS_INDICATIVOS','','PUBLICIDADE','adHoc_Ext_PUB_SINAIS_INDICATIVOS','','88','Arquivo/CMA/0.9-Actividades económicas/Industria/Publicidade','E','Atendimento ','Sinais indicativos para estabelecimentos de restauração e/ou bebidas misto');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_OCUPACAO_ESPACO_PUBLICO','','OCUPAÇÃO DO ESPAÇO PÚBLICO MUNICIPAL','adHoc_Ext_OCUPACAO_ESPACO_PUBLICO','','89','Arquivo/CMA/0.2-Serviços administrativos/Taxas e Licenças/Ocupação de espaço público municipal','E','Atendimento','Ocupação de espaço público municipal');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_PROT_FOGO_ARTIFICIO','','PROTECÇÃO CIVIL','adHoc_Ext_PROT_FOGO_ARTIFICIO','','90','Arquivo/CMA/0.7-Segurança pública/Protecção civil','E','Atendimento_ProteccaoCivil','Utilização de fogo de artifício em espaço rural');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_PROT_QUEIMADAS','','PROTECÇÃO CIVIL','adHoc_Ext_PROT_QUEIMADAS','','91','Arquivo/CMA/0.7-Segurança pública/Protecção civil','E','Atendimento_ProteccaoCivil','Realização de queimadas');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_COMP_JUNCAO_ELEMENTOS','','PROCESSOS COMPLEMENTARES','adHoc_Ext_COMP_JUNCAO_ELEMENTOS','','52','Arquivo/CMA/Diversos','E','Atendimento',' Junção de elementos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_COMP_AVERBAMENTOS','','PROCESSOS COMPLEMENTARES','adHoc_Ext_COMP_AVERBAMENTOS','','92','Arquivo/CMA/Diversos','E','Atendimento','Averbamento');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_COMP_PRORROGACAO_PRAZOS','','PROCESSOS COMPLEMENTARES','adHoc_Ext_COMP_PRORROGACAO_PRAZOS','','54','Arquivo/CMA/Diversos','E','Atendimento',' Prorrogação de prazos');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Ext_REQ_GENERICO_EXT','','REQUERIMENTO GENÉRICO EXTERNO','adHoc_Ext_REQ_GENERICO_EXT','','','Arquivo/CMA/Diversos','E','Todos','');
insert into cma_tipo_processo (id_tipo_processo, id_tipo_processo_num, grupo, codigo_subgrupo, subgrupo,id_tipo_requerimento,pasta_processo_base, tipo_processo_macro,perfil_responsavel, descricao) values ('adHoc_Int_REQ_GENERICO_INT','','REQUERIMENTO GENÉRICO INTERNO','adHoc_Int_REQ_GENERICO_INT','','','Arquivo/CMA/Diversos','I','Todos','');

