CREATE SEQUENCE SEQ_NODEKEY INCREMENT BY 1 MINVALUE 1 CACHE 20;

CREATE TABLE ACTIVE_NODE 
(
  NODEKEY VARCHAR2(50) NOT NULL , 
  EXPIRATION DATE NOT NULL , 
  CONSTRAINT ACTIVE_NODE_PK PRIMARY KEY ( NODEKEY )  ENABLE 
);

CREATE OR REPLACE 
PROCEDURE GET_NEXT_NODEKEY 
(
  RETNODEKEY OUT NUMBER  
) IS 
BEGIN
  SELECT SEQ_NODEKEY.NEXTVAL INTO RETNODEKEY FROM DUAL;
END;

CREATE SEQUENCE sqe_sorefresh INCREMENT BY 1 MINVALUE 1 CACHE 20;

CREATE TABLE  sharedobjectrefresh (
  id number,
  flowid number ,
  CONSTRAINT sorefresh_pk PRIMARY KEY ( id )  ENABLE 
);