/*****************************************************************************************
    Infosistema iFlow - workflow and BPM platform
    Copyright(C) 2002-2012 Infosistema, S.A.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    www.infosistema.com
    iflow@infosistema.com
    Av. Jose Gomes Ferreira, 11 3rd floor, s.34
    Miraflores
    1495-139 Alges Portugal
****************************************************************************************/
/* Generated By:JavaCC: Do not edit this line. InstructionCompilerConstants.java */
package pt.iflow.api.sch;

public interface InstructionCompilerConstants {

  int EOF = 0;
  int EOL = 4;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int DIVIDE = 8;
  int EXP = 9;
  int ASSIGN = 10;
  int EQUAL = 11;
  int NON_EQUAL = 12;
  int GREATER = 13;
  int GREATER_OR_EQUAL = 14;
  int SMALLER = 15;
  int SMALLER_OR_EQUAL = 16;
  int AND = 17;
  int OR = 18;
  int NOT = 19;
  int VERDADEIRO = 20;
  int FALSO = 21;
  int TRUE = 22;
  int FALSE = 23;
  int CONSTANT = 24;
  int FLOAT = 25;
  int INTEGER = 26;
  int DIGIT = 27;
  int ID = 28;
  int LETTER = 29;
  int PAR_OPEN = 30;
  int PAR_CLOSE = 31;
  int RECT_OPEN = 32;
  int RECT_CLOSE = 33;
  int TRASH = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"verdadeiro\"",
    "\"falso\"",
    "\"true\"",
    "\"false\"",
    "<CONSTANT>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<TRASH>",
  };

}
