#Properties
#Thu Oct 02 17:45:34 BST 2025
crypto-api.version=1.0.3
iflow.home=C\:\\Users\\jcosta\\git\\iFlowRoot\\iflow-web/iflow-home
dms-connector.version=0.0.7-R20100908
maven.test.skip=true
alfresco-connector.version=0.0.7-R20100908
project.build.sourceEncoding=UTF-8
iflow.buildnumber=20180704
iflow.version=4.2.6-R20180704
iflow.baseversion=4.2.6
