package pt.iknow.floweditor;

import java.util.ArrayList;

/*******************************************************************************
 * 
 * Project FLOW EDITOR
 * 
 * class: EncontraComponente
 * 
 * desc: dialogo para encontrar um dado bloco
 * 
 ******************************************************************************/

public class EncontraComponente extends javax.swing.JDialog {
  private static final long serialVersionUID = 2634968116134367146L;
  
  LibrarySet cbBibs = null;
  Componente_Biblioteca compBib = null;

  /** Creates new form EncontraComponente */
  public EncontraComponente(java.awt.Frame parent, boolean modal, LibrarySet b) {
    super(parent, modal);
    initComponents();
    setTitle(Mesg.TitleChooseCB);
    cbBibs = b;
    setSize(300, 330);
    jTextField1ActionPerformed(null);
    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  private void initComponents() {// GEN-BEGIN:initComponents
    jPanel2 = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jButton2 = new javax.swing.JButton();

    setModal(true);
    setResizable(false);
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentResized(java.awt.event.ComponentEvent evt) {
        formComponentResized(evt);
      }
    });

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    jTextField1.setMaximumSize(new java.awt.Dimension(150, 20));
    jTextField1.setMinimumSize(new java.awt.Dimension(150, 20));
    jTextField1.setPreferredSize(new java.awt.Dimension(150, 20));
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    jPanel2.add(jTextField1);

    jButton1.setText(Mesg.Search);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jPanel2.add(jButton1);

    getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setMaximumSize(new java.awt.Dimension(250, 220));
    jScrollPane1.setMinimumSize(new java.awt.Dimension(250, 220));
    jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 220));
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });

    jScrollPane1.setViewportView(jList1);

    jPanel1.add(jScrollPane1);

    jButton2.setText(Mesg.Cancelar);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jPanel1.add(jButton2);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// GEN-END:initComponents

  private void formComponentResized(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentResized
    // Add your handling code here:
  }// GEN-LAST:event_formComponentResized

  /*****************************************************************************
   * EXIT
   */
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    // Add your handling code here:
    dispose();
  }// GEN-LAST:event_jButton2ActionPerformed

  /*****************************************************************************
   * selecciona um componente
   */
  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jList1MouseClicked
    // Add your handling code here:

    if (evt.getClickCount() == 2) {
      Componente_Biblioteca selected = (Componente_Biblioteca) jList1.getSelectedValue();
      compBib = selected;
      if (compBib != null)
        dispose();

    }
  }// GEN-LAST:event_jList1MouseClicked

  /*****************************************************************************
   * cria lista de componentes encontrados
   */
  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

    ArrayList<Componente_Biblioteca> alMatch = new ArrayList<Componente_Biblioteca>();

    String[] saLibs = cbBibs.getLibraryKeys();
    for (int int_lib = 0; int_lib < saLibs.length; int_lib++) {
      Library b = cbBibs.getLibrary(saLibs[int_lib]);
      alMatch.addAll(b.procuraBiblioteca(jTextField1.getText()));
    }

    if (alMatch.size() > 0) {
      Object[] list = new Object[alMatch.size()];
      for (int i = 0; i < alMatch.size(); i++) {
        list[i] = alMatch.get(i);
      }
      jList1.setListData(list);
    }
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // Add your handling code here:
    jTextField1ActionPerformed(null);
  }// GEN-LAST:event_jButton1ActionPerformed

  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }// GEN-LAST:event_closeDialog

  /**
   * @param args
   *          the command line arguments
   * 
   * public static void main(String args[]) { new EncontraComponente(new
   * javax.swing.JFrame(), true,null).show(); }
   * 
   */
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JList jList1;
  // End of variables declaration//GEN-END:variables

}
